class ResponseCodes {
  static DATA_CREATED = 'DATA_CREATED';
  static DATA_RETRIEVED = 'DATA_RETRIEVED';
  static LIST_RETRIEVED = 'LIST_RETRIEVED';
  static DATA_MODIFIED = 'DATA_MODIFIED';
  static DATA_DELETED = 'DATA_DELETED';

  // ERROR CODES
  static INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
  static NOT_FOUND = 'NOT_FOUND';

  static BAD_REQUEST = 'BAD_REQUEST';
  static RESOURCE_CONFLICT = 'RESOURCE_CONFLICT';
  static UNAUTHORIZE = 'UNAUTHORIZE';
}

export default ResponseCodes;
